#!/bin/bash

# ============================================================================
# Configure API URL for Production
# ============================================================================
#
# This script retrieves the deployed API Gateway URL from AWS CloudFormation
# and updates the .env.production file with the correct endpoint.
#
# Usage:
#   ./configure-api.sh [stack-name]
#
# Default stack name: agent-ui-api
#
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
STACK_NAME="${1:-agent-ui-api}"
ENV_FILE=".env.production"

echo -e "${BLUE}============================================================================${NC}"
echo -e "${BLUE}Configure API URL for Production${NC}"
echo -e "${BLUE}============================================================================${NC}"
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ Error: AWS CLI is not installed${NC}"
    echo "Install it with: brew install awscli"
    exit 1
fi

echo -e "${BLUE}📡 Retrieving API URL from CloudFormation stack: ${STACK_NAME}${NC}"
echo ""

# Get API URL from CloudFormation stack
API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
    --output text 2>/dev/null)

if [ -z "$API_URL" ] || [ "$API_URL" == "None" ]; then
    echo -e "${RED}❌ Error: Could not retrieve API URL from stack '${STACK_NAME}'${NC}"
    echo ""
    echo "Possible reasons:"
    echo "  1. Stack does not exist"
    echo "  2. Stack has not been deployed yet"
    echo "  3. Stack name is incorrect"
    echo ""
    echo "To deploy the backend API:"
    echo "  cd ../api"
    echo "  ./deploy.sh"
    echo ""
    exit 1
fi

echo -e "${GREEN}✅ Found API URL: ${API_URL}${NC}"
echo ""

# Backup existing .env.production if it exists
if [ -f "$ENV_FILE" ]; then
    BACKUP_FILE="${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${YELLOW}📦 Backing up existing ${ENV_FILE} to ${BACKUP_FILE}${NC}"
    cp "$ENV_FILE" "$BACKUP_FILE"
    echo ""
fi

# Update .env.production file
echo -e "${BLUE}📝 Updating ${ENV_FILE}${NC}"

# Replace the API URL in the file
if [ -f "$ENV_FILE" ]; then
    # Use sed to replace the VITE_API_BASE_URL line
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|^VITE_API_BASE_URL=.*|VITE_API_BASE_URL=${API_URL}|" "$ENV_FILE"
    else
        # Linux
        sed -i "s|^VITE_API_BASE_URL=.*|VITE_API_BASE_URL=${API_URL}|" "$ENV_FILE"
    fi
else
    # Create new file if it doesn't exist
    cat > "$ENV_FILE" << EOF
# Production Environment Configuration
# Generated by configure-api.sh on $(date)

VITE_API_BASE_URL=${API_URL}
EOF
fi

echo -e "${GREEN}✅ Successfully updated ${ENV_FILE}${NC}"
echo ""

# Display the configuration
echo -e "${BLUE}Current configuration:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
grep "^VITE_API_BASE_URL=" "$ENV_FILE" || echo "VITE_API_BASE_URL=${API_URL}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${GREEN}✅ Configuration complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  1. Build the frontend for production:"
echo "     npm run build"
echo ""
echo "  2. Test the API connection:"
echo "     ./test-api-connection.sh"
echo ""
echo "  3. Deploy to AWS Amplify:"
echo "     git add .env.production"
echo "     git commit -m 'Update production API URL'"
echo "     git push"
echo ""

