default_agent: OnboardingAgent_Agent
agents:
  OnboardingAgent_Agent:
    name: OnboardingAgent_Agent
    language: python
    node_version: null
    entrypoint: /Users/adhavle/Documents/SDFC Industries/MWC-demo/OnboardingAgent/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: /Users/adhavle/Documents/SDFC Industries/MWC-demo/OnboardingAgent/src
    aws:
      execution_role: arn:aws:iam::905767016260:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-98b4eb4cce
      execution_role_auto_create: false
      account: '905767016260'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-905767016260-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: OnboardingAgent_Agent-Pgs8nUGuuS
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:runtime/OnboardingAgent_Agent-Pgs8nUGuuS
      agent_session_id: c16072ea-ccf6-4a25-9c97-540680a7e1b4
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
